FROM oven/bun:latest

WORKDIR /usr/src/app
COPY  ./bun.lock  ./bun.lock
COPY  ./package.json   ./package.json
COPY  ./tsconfig.json   ./tsconfig.json
COPY   ./packages     ./packages

COPY  ./apps/web   ./apps/web

RUN bun install
RUN  bun run db:migrate
RUN  npm run build



EXPOSE  3000 
 CMD [ "bun" ,"run", "start:web" ]